---
title: "Integer Equivalence Classes and Symmetries"
format:
  revealjs:
    theme: solarized
    slide-number: true
---


## Class Session Goals

- Prove the Division Algorithm
- Explore the Integers Modulo $n$


---


## Well Ordering of the Natural Numbers

A set $S$ is **well-ordered** if every nonempty subset of $S$ contains a least element.

**Principle of Well-Ordering.** Every nonempty subset of the natural numbers is well-ordered.

In this class the natural numbers are $\mathbb{N}=\{0, 1, 2, 3, \ldots\}$.

---

## What about  the integers?

The integers $\mathbb{Z}$ are **not** well-ordered.

For example,

$$
\{\ldots,-4,-3,-2,-1\}
$$

has no least element.

---

## Division Algorithm

**Division Algorithm.** Let $a$ and $b$ be integers, with $b>0$. Then there exist unique integers $q$ and $r$ such that $a=bq+r$ where $0\leq r<b$.

The proof has three parts:

1. **Existence:** Show that $q$ and $r$ exist.
2. Verify $0\leq r<b$
3. **Uniqueness:** Show that no other $q$ and $r$ can satisfy these conditions.


---

## Theorem 2.2.2

Let $a$ and $b$ be nonzero integers. Then there exist integers $r$ and $s$ such that

$$
\gcd(a,b) = ar + bs.
$$

Furthermore, the greatest common divisor of $a$ and $b$ is unique.


If $\gcd(a,b) = 1$, we say that $a$ and $b$ are *relatively prime*.

---

## Integers Mod n

**Equivalence Relation:** Two integers $a$ and $b$ are equivalent mod $n$ if $n$ divides $a-b$.

The integers mod $n$ partition $\mathbb Z$ into $n$ different equivalence classes; we denote the set of these equivalence classes by $\mathbb Z_n$.  $\mathbb Z_n=\{[0], [1], [2], \ldots, [n-1]\}$. Recall $[i]=\{s \in \mathbb Z : s=nl+i \text{ for some } l\}$.

Sometime we will get lazy and use $\{ 0,1,\ldots,n-1 \}$


---

## Extending Addintion and Multiplication

For two integers $a$ and $b$, define addition modulo $n$ to be $(a+b)\pmod n$; that is, the remainder when $a+b$ is divided by $n$.

Similarly, multiplication modulo $n$ is defined as $(ab)\pmod n$, the remainder when $ab$ is divided by $n$.

---

## Note on defining functions and operations on equivalence classes.

When defining functions or operations on equivalence classes we must verify that the are *well defined*.
For example,

We must show that if

$$
[a]=[a'] \qquad \text{and} \qquad [b]=[b'],
$$

then

$$
[a+b]=[a'+b'].
$$


---

## Checking

I'll check the first argument of the operation; the second argument is the same. Assume $a \sim a'$. I need to show that $a+b \sim a'+b$.

::: {.callout-important}
Whenever an operation is defined on equivalence classes, we must check that different representatives of the same classes give the same result.
:::

---

## Pathological Example

Consider the rational numbers $\mathbb Q$. Every rational number can be represented as a fraction

$$
\frac{a}{b}, \qquad b\neq 0.
$$

Suppose we try to define a function $f:\mathbb Q\to\mathbb Z$ by

$$
f\left(\frac{a}{b}\right)=a+b.
$$


---

## Addition table for $\mathbb Z_5$


$$
\begin{array}{c|ccccc}
+ & 0 & 1 & 2 & 3 & 4 \\
\hline
0 & 0 & 1 & 2 & 3 & 4 \\
1 & 1 & 2 & 3 & 4 & 0 \\
2 & 2 & 3 & 4 & 0 & 1 \\
3 & 3 & 4 & 0 & 1 & 2 \\
4 & 4 & 0 & 1 & 2 & 3
\end{array}
$$


---

## Multiplication table for $\mathbb Z_8$:


$$
\begin{array}{c|cccccccc}
\cdot & 0 & 1 & 2 & 3 & 4 & 5 & 6 & 7 \\
\hline
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
1 & 0 & 1 & 2 & 3 & 4 & 5 & 6 & 7 \\
2 & 0 & 2 & 4 & 6 & 0 & 2 & 4 & 6 \\
3 & 0 & 3 & 6 & 1 & 4 & 7 & 2 & 5 \\
4 & 0 & 4 & 0 & 4 & 0 & 4 & 0 & 4 \\
5 & 0 & 5 & 2 & 7 & 4 & 1 & 6 & 3 \\
6 & 0 & 6 & 4 & 2 & 0 & 6 & 4 & 2 \\
7 & 0 & 7 & 6 & 5 & 4 & 3 & 2 & 1
\end{array}
$$


---

## Units of $\mathbb Z_8$

$$
\newcommand{\blue}[1]{\bbox[cyan]{#1}}
\begin{array}{c|cccccccc}
\cdot & 0 & \blue{1} & 2 & \blue{3} & 4 & \blue{5} & 6 & \blue{7} \\
\hline
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
\blue{1} & 0 & 1 & 2 & 3 & 4 & 5 & 6 & 7 \\
2 & 0 & 2 & 4 & 6 & 0 & 2 & 4 & 6 \\
\blue{3} & 0 & 3 & 6 & 1 & 4 & 7 & 2 & 5 \\
4 & 0 & 4 & 0 & 4 & 0 & 4 & 0 & 4 \\
\blue{5} & 0 & 5 & 2 & 7 & 4 & 1 & 6 & 3 \\
6 & 0 & 6 & 4 & 2 & 0 & 6 & 4 & 2 \\
\blue{7} & 0 & 7 & 6 & 5 & 4 & 3 & 2 & 1
\end{array}
$$

---


## Activity

Construct the multiplication tables for $\mathbb Z_6$.




## Addition Table for $\mathbb Z_6$


$$
\begin{array}{c|c|c|c|c|c|c}
 + & 0 & 1 & 2 & 3 & 4 & 5  \\
\hline
0 &  &  &  &  &  &  &  \\
\hline
1 &  &  &  &  &  &  &  \\
\hline
2 &  &  &  &  &  &  &  \\
\hline
3 &  &  &  &  &  &  &  \\
\hline
4 &  &  &  &  &  &  &  \\
\hline
5 &  &  &  &  &  &  &  \\
\end{array}
$$



---

## Multiplication Table for $\mathbb Z_6$


$$
\begin{array}{c|c|c|c|c|c|c}
 \cdot & 0 & 1 & 2 & 3 & 4 & 5  \\
\hline
0 &  &  &  &  &  &  &  \\
\hline
1 &  &  &  &  &  &  &  \\
\hline
2 &  &  &  &  &  &  &  \\
\hline
3 &  &  &  &  &  &  &  \\
\hline
4 &  &  &  &  &  &  &  \\
\hline
5 &  &  &  &  &  &  &  \\
\end{array}
$$

What are the units?

---

## Proposition 3.1.4.

Let $\mathbb Z_n$ be the set of equivalence classes of the integers mod $n$ and $a,b,c \in \mathbb Z_n$.

1. Addition and multiplication are commutative:

$$
\begin{aligned}
a+b &\equiv b+a \pmod n \\
ab &\equiv ba \pmod n.
\end{aligned}
$$

2. Addition and multiplication are associative:

$$
\begin{aligned}
(a+b)+c &\equiv a+(b+c)\pmod n \\
(ab)c &\equiv a(bc)\pmod n.
\end{aligned}
$$

## Proposition 3.1.4. Continued

3. There are both additive and multiplicative identities:

$$
\begin{aligned}
a+0 &\equiv a \pmod n \\
a\cdot 1 &\equiv a \pmod n.
\end{aligned}
$$

4. Multiplication distributes over addition:

$$
a(b+c)\equiv ab+ac\pmod n.
$$

## Proposition 3.1.4. Continued More

5. For every integer $a$ there is an additive inverse $-a$:

$$
a+(-a)\equiv 0\pmod n.
$$

6. Let $a$ be a nonzero integer. Then $\gcd(a,n)=1$ if and only if there exists a multiplicative inverse $b$ for $a\pmod n$; that is, a nonzero integer $b$ such that

$$
ab\equiv 1\pmod n.
$$

---





## Polygonal Symmeteties Revisted

$$
\begin{array}{c|c|c|c|c|c|c}
 & e & r_1 & r_2 & f_A & f_B & f_C  \\
\hline
e &  &  &  &  &  &  &  \\
\hline
r_1 &  &  &  &  &  &  &  \\
\hline
r_2 &  &  &  &  &  &  &  \\
\hline
f_A &  &  &  &  &  &  &  \\
\hline
f_B &  &  &  &  &  &  &  \\
\hline
f_C &  &  &  &  &  &  &  \\
\end{array}
$$


---

