project:
  type: website
  output-dir: docs

website:
  title: "Math 393 - Abstract Algebra"
  sidebar:
    contents:
      - text: "Home"
        file: index.qmd

      - section: "Class Material"
        contents:
          - file: classes/01/worksheet.qmd
          - file: classes/01/slides.qmd
          - file: classes/02/slides.qmd
          - file: classes/02/worksheet.qmd
          - file: classes/03/worksheet.qmd
          - file: classes/03/slides.qmd
          - file: classes/04/slides.qmd
          - file: classes/05/slides.qmd
  

format:
  html:
    theme: cosmo
    toc: true
    html-math-method: mathjax