project:
  type: website
  output-dir: docs

format:
  html:
    toc: true
    math: mathjax

website:
  title: "Math 393 - Abstract Algebra"
  sidebar:
    contents:
    - text: "Home"
      file: index.qmd
    - text: "Syllabus"
      file: syllabus.qmd