---
title: "Slides: Cyclic Groups"

format:
  revealjs:
    theme: solarized
    slide-number: true
---

## Class Session Goals

- Understand the structure of groups generated by a single element
- Determine when an element generates a group
- Describe the subgroups of a cyclic group
- Relate the order of an element to the order of the cyclic subgroup it generates

---

## Generator, Notation, and Order

Let $G$ be a group and let $a \in G$. The subgroup generated by $a$ is $\langle a \rangle = \{a^n : n \in \mathbb{Z}\}$.

A group $G$ is **cyclic** if there exists an element $a \in G$ such that $G = \langle a \rangle$.

In this case, $a$ is called a **generator** of $G$.

The **order** of $a$ is the smallest positive integer $n$ such that $a^n=e$, if such an integer exists.

---

## Examples of Groups Generated by one element

The group of integers under addition is cyclic:

$$
\mathbb{Z}=\langle 1\rangle=\langle -1\rangle.
$$

The group $\mathbb{Z}_n$ under addition is cyclic:

$$
\mathbb{Z}_n=\langle 1\rangle.
$$

In $U(18)$, $\langle 5\rangle$ and $\langle 11\rangle$ are generators, but $\langle 7\rangle$ is not.

---

## Cayley Table for $U(18)$

<table style="border-collapse: collapse; table-layout: fixed; width: 490px;">

<colgroup>

<col style="width: 70px;"><col style="width: 70px;"><col style="width: 70px;">

<col style="width: 70px;"><col style="width: 70px;"><col style="width: 70px;">

<col style="width: 70px;">

</colgroup>

<tr>

<th style="border: 1px solid black; height: 45px; text-align: right;">$\cdot$</th>

<th style="border: 1px solid black; text-align: right;">$1$</th>

<th style="border: 1px solid black; text-align: right;">$5$</th>

<th style="border: 1px solid black; text-align: right;">$7$</th>

<th style="border: 1px solid black; text-align: right;">$11$</th>

<th style="border: 1px solid black; text-align: right;">$13$</th>

<th style="border: 1px solid black; text-align: right;">$17$</th>

</tr>

<tr>

<th style="border: 1px solid black; height: 45px; text-align: right;">$1$</th>

<td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$5$</td><td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$11$</td><td style="border: 1px solid black; text-align: right;">$13$</td><td style="border: 1px solid black; text-align: right;">$17$</td>

</tr>

<tr>

<th style="border: 1px solid black; height: 45px; text-align: right;">$5$</th>

<td style="border: 1px solid black; text-align: right;">$5$</td><td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$17$</td><td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$11$</td><td style="border: 1px solid black; text-align: right;">$13$</td>

</tr>

<tr>

<th style="border: 1px solid black; height: 45px; text-align: right;">$7$</th>

<td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$17$</td><td style="border: 1px solid black; text-align: right;">$13$</td><td style="border: 1px solid black; text-align: right;">$5$</td><td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$11$</td>

</tr>

<tr>

<th style="border: 1px solid black; height: 45px; text-align: right;">$11$</th>

<td style="border: 1px solid black; text-align: right;">$11$</td><td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$5$</td><td style="border: 1px solid black; text-align: right;">$13$</td><td style="border: 1px solid black; text-align: right;">$17$</td><td style="border: 1px solid black; text-align: right;">$7$</td>

</tr>

<tr>

<th style="border: 1px solid black; height: 45px; text-align: right;">$13$</th>

<td style="border: 1px solid black; text-align: right;">$13$</td><td style="border: 1px solid black; text-align: right;">$11$</td><td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$17$</td><td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$5$</td>

</tr>

<tr>

<th style="border: 1px solid black; height: 45px; text-align: right;">$17$</th>

<td style="border: 1px solid black; text-align: right;">$17$</td><td style="border: 1px solid black; text-align: right;">$13$</td><td style="border: 1px solid black; text-align: right;">$11$</td><td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$5$</td><td style="border: 1px solid black; text-align: right;">$1$</td>

</tr>

</table>

---

## Subgroup Lattice for $U(18)$

```{mermaid}

flowchart TB

    U["U(18) = {1, 5, 7, 11, 13, 17}"]

    H3["{1, 7, 13}"]

    H2["{1, 17}"]

    E["{1}"]

    U --- H3

    U --- H2

    H3 --- E

    H2 --- E
```

---

## Quick Activty

For each element of $\mathbb Z_{12}$, classify each element as a generator of the cyclic group or not at generator.  For the elements that do not generate $\mathbb Z_{12}$, what is their order?

What to the generators have in common?  What do the non-generators have in common?

---

## Theorem 4.1.3

**Theorem.** Let $G$ be a group and $a \in G$. Then $\langle a \rangle = \{a^k : k \in \mathbb{Z}\}$
is a subgroup of $G$.

**Proof** Use Subgroup Criteria.

. . . 

Furthermore, $\langle a \rangle$ is the smallest subgroup of $G$ that contains $a$. The subgroup $\langle a \rangle$ is called the **cyclic subgroup generated by $a$**.

---

## Theorem 4.1.9

**Theorem.** Every cyclic group is abelian.

**Proof.** Let $G$ be cyclic. Then $G=\langle a\rangle$ for some $a\in G$.

If $g,h\in G$, then there exist integers $r$ and $s$ such that

$g=a^r$ and $h=a^s$.

Therefore,

$$
gh=a^ra^s=a^{r+s}=a^{s+r}=a^sa^r=hg.
$$

Hence $G$ is abelian.

---

## Theorem 4.1.10

**Theorem.** Every subgroup of a cyclic group is cyclic.



---

## Theorem 4.1.12

**Theorem.** Let $G=\langle a\rangle$ be a cyclic group of order $n$. THen $a^k=e$ if and only if $n$ divides $k$.

---

## Theorem 4.1.13

**Theorem.** Let  $G=\langle a\rangle$ be a cyclic group of order $n$. If $b=a^k$ then the order of $b$ is $\frac{n}{d}$ where $d=gcd(k,n)$.

. . . 

Thus the possible orders of elements in a finite cyclic group are precisely the positive divisors of the order of the group.  If $k$ is relatively prime to $n$ then $G=\langle b\rangle$.

---





## Cayley Table for $U(20)$

<table style="border-collapse: collapse; table-layout: fixed; width: 630px;">
<colgroup>
<col style="width: 70px;"><col style="width: 70px;"><col style="width: 70px;">
<col style="width: 70px;"><col style="width: 70px;"><col style="width: 70px;">
<col style="width: 70px;"><col style="width: 70px;"><col style="width: 70px;">
</colgroup>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$\cdot$</th>
<th style="border: 1px solid black; text-align: right;">$1$</th>
<th style="border: 1px solid black; text-align: right;">$3$</th>
<th style="border: 1px solid black; text-align: right;">$7$</th>
<th style="border: 1px solid black; text-align: right;">$9$</th>
<th style="border: 1px solid black; text-align: right;">$11$</th>
<th style="border: 1px solid black; text-align: right;">$13$</th>
<th style="border: 1px solid black; text-align: right;">$17$</th>
<th style="border: 1px solid black; text-align: right;">$19$</th>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$1$</th>
<td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$3$</td><td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$9$</td><td style="border: 1px solid black; text-align: right;">$11$</td><td style="border: 1px solid black; text-align: right;">$13$</td><td style="border: 1px solid black; text-align: right;">$17$</td><td style="border: 1px solid black; text-align: right;">$19$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$3$</th>
<td style="border: 1px solid black; text-align: right;">$3$</td><td style="border: 1px solid black; text-align: right;">$9$</td><td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$13$</td><td style="border: 1px solid black; text-align: right;">$19$</td><td style="border: 1px solid black; text-align: right;">$11$</td><td style="border: 1px solid black; text-align: right;">$17$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$7$</th>
<td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$9$</td><td style="border: 1px solid black; text-align: right;">$3$</td><td style="border: 1px solid black; text-align: right;">$17$</td><td style="border: 1px solid black; text-align: right;">$11$</td><td style="border: 1px solid black; text-align: right;">$19$</td><td style="border: 1px solid black; text-align: right;">$13$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$9$</th>
<td style="border: 1px solid black; text-align: right;">$9$</td><td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$3$</td><td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$19$</td><td style="border: 1px solid black; text-align: right;">$17$</td><td style="border: 1px solid black; text-align: right;">$13$</td><td style="border: 1px solid black; text-align: right;">$11$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$11$</th>
<td style="border: 1px solid black; text-align: right;">$11$</td><td style="border: 1px solid black; text-align: right;">$13$</td><td style="border: 1px solid black; text-align: right;">$17$</td><td style="border: 1px solid black; text-align: right;">$19$</td><td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$3$</td><td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$9$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$13$</th>
<td style="border: 1px solid black; text-align: right;">$13$</td><td style="border: 1px solid black; text-align: right;">$19$</td><td style="border: 1px solid black; text-align: right;">$11$</td><td style="border: 1px solid black; text-align: right;">$17$</td><td style="border: 1px solid black; text-align: right;">$3$</td><td style="border: 1px solid black; text-align: right;">$9$</td><td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$7$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$17$</th>
<td style="border: 1px solid black; text-align: right;">$17$</td><td style="border: 1px solid black; text-align: right;">$11$</td><td style="border: 1px solid black; text-align: right;">$19$</td><td style="border: 1px solid black; text-align: right;">$13$</td><td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$9$</td><td style="border: 1px solid black; text-align: right;">$3$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$19$</th>
<td style="border: 1px solid black; text-align: right;">$19$</td><td style="border: 1px solid black; text-align: right;">$17$</td><td style="border: 1px solid black; text-align: right;">$13$</td><td style="border: 1px solid black; text-align: right;">$11$</td><td style="border: 1px solid black; text-align: right;">$9$</td><td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$3$</td><td style="border: 1px solid black; text-align: right;">$1$</td>
</tr>
</table>

---

## Subgroup Lattice for $U(20)$

```{mermaid}
flowchart TB
    U["U(20)"]

    H1["{1, 3, 7, 9}"]
    H2["{1, 9, 13, 17}"]
    H3["{1, 9, 11, 19}"]

    K9["{1, 9}"]
    K11["{1, 11}"]
    K19["{1, 19}"]

    E["{1}"]

    U --- H1
    U --- H2
    U --- H3

    H1 --- K9
    H2 --- K9

    H3 --- K9
    H3 --- K11
    H3 --- K19

    K9 --- E
    K11 --- E
    K19 --- E
```

---



## Cayley Table for $Q_8$

<table style="border-collapse: collapse; table-layout: fixed; width: 720px; font-size: 0.72em;">
<colgroup>
<col style="width: 80px;"><col style="width: 80px;"><col style="width: 80px;">
<col style="width: 80px;"><col style="width: 80px;"><col style="width: 80px;">
<col style="width: 80px;"><col style="width: 80px;"><col style="width: 80px;">
</colgroup>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$\cdot$</th>
<th style="border: 1px solid black; text-align: right;">$I$</th>
<th style="border: 1px solid black; text-align: right;">$-I$</th>
<th style="border: 1px solid black; text-align: right;">$A$</th>
<th style="border: 1px solid black; text-align: right;">$-A$</th>
<th style="border: 1px solid black; text-align: right;">$B$</th>
<th style="border: 1px solid black; text-align: right;">$-B$</th>
<th style="border: 1px solid black; text-align: right;">$C$</th>
<th style="border: 1px solid black; text-align: right;">$-C$</th>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$I$</th>
<td style="border: 1px solid black; text-align: right;">$I$</td><td style="border: 1px solid black; text-align: right;">$-I$</td><td style="border: 1px solid black; text-align: right;">$A$</td><td style="border: 1px solid black; text-align: right;">$-A$</td><td style="border: 1px solid black; text-align: right;">$B$</td><td style="border: 1px solid black; text-align: right;">$-B$</td><td style="border: 1px solid black; text-align: right;">$C$</td><td style="border: 1px solid black; text-align: right;">$-C$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$-I$</th>
<td style="border: 1px solid black; text-align: right;">$-I$</td><td style="border: 1px solid black; text-align: right;">$I$</td><td style="border: 1px solid black; text-align: right;">$-A$</td><td style="border: 1px solid black; text-align: right;">$A$</td><td style="border: 1px solid black; text-align: right;">$-B$</td><td style="border: 1px solid black; text-align: right;">$B$</td><td style="border: 1px solid black; text-align: right;">$-C$</td><td style="border: 1px solid black; text-align: right;">$C$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$A$</th>
<td style="border: 1px solid black; text-align: right;">$A$</td><td style="border: 1px solid black; text-align: right;">$-A$</td><td style="border: 1px solid black; text-align: right;">$-I$</td><td style="border: 1px solid black; text-align: right;">$I$</td><td style="border: 1px solid black; text-align: right;">$C$</td><td style="border: 1px solid black; text-align: right;">$-C$</td><td style="border: 1px solid black; text-align: right;">$-B$</td><td style="border: 1px solid black; text-align: right;">$B$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$-A$</th>
<td style="border: 1px solid black; text-align: right;">$-A$</td><td style="border: 1px solid black; text-align: right;">$A$</td><td style="border: 1px solid black; text-align: right;">$I$</td><td style="border: 1px solid black; text-align: right;">$-I$</td><td style="border: 1px solid black; text-align: right;">$-C$</td><td style="border: 1px solid black; text-align: right;">$C$</td><td style="border: 1px solid black; text-align: right;">$B$</td><td style="border: 1px solid black; text-align: right;">$-B$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$B$</th>
<td style="border: 1px solid black; text-align: right;">$B$</td><td style="border: 1px solid black; text-align: right;">$-B$</td><td style="border: 1px solid black; text-align: right;">$-C$</td><td style="border: 1px solid black; text-align: right;">$C$</td><td style="border: 1px solid black; text-align: right;">$-I$</td><td style="border: 1px solid black; text-align: right;">$I$</td><td style="border: 1px solid black; text-align: right;">$A$</td><td style="border: 1px solid black; text-align: right;">$-A$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$-B$</th>
<td style="border: 1px solid black; text-align: right;">$-B$</td><td style="border: 1px solid black; text-align: right;">$B$</td><td style="border: 1px solid black; text-align: right;">$C$</td><td style="border: 1px solid black; text-align: right;">$-C$</td><td style="border: 1px solid black; text-align: right;">$I$</td><td style="border: 1px solid black; text-align: right;">$-I$</td><td style="border: 1px solid black; text-align: right;">$-A$</td><td style="border: 1px solid black; text-align: right;">$A$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$C$</th>
<td style="border: 1px solid black; text-align: right;">$C$</td><td style="border: 1px solid black; text-align: right;">$-C$</td><td style="border: 1px solid black; text-align: right;">$B$</td><td style="border: 1px solid black; text-align: right;">$-B$</td><td style="border: 1px solid black; text-align: right;">$-A$</td><td style="border: 1px solid black; text-align: right;">$A$</td><td style="border: 1px solid black; text-align: right;">$-I$</td><td style="border: 1px solid black; text-align: right;">$I$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$-C$</th>
<td style="border: 1px solid black; text-align: right;">$-C$</td><td style="border: 1px solid black; text-align: right;">$C$</td><td style="border: 1px solid black; text-align: right;">$-B$</td><td style="border: 1px solid black; text-align: right;">$B$</td><td style="border: 1px solid black; text-align: right;">$A$</td><td style="border: 1px solid black; text-align: right;">$-A$</td><td style="border: 1px solid black; text-align: right;">$I$</td><td style="border: 1px solid black; text-align: right;">$-I$</td>
</tr>
</table>

---

## Subgroup Lattice for $Q_8$

```{mermaid}
flowchart TB
    Q["Q<sub>8</sub>"]
    A["{I, -I, A, -A}"]
    B["{I, -I, B, -B}"]
    C["{I, -I, C, -C}"]
    M["{I, -I}"]
    E["{I}"]

    Q --- A
    Q --- B
    Q --- C
    A --- M
    B --- M
    C --- M
    M --- E
```

---

## Cayley Table for the Symmetries of the Square

<table style="border-collapse: collapse; table-layout: fixed; width: 720px; font-size: 0.72em;">
<colgroup>
<col style="width: 80px;"><col style="width: 80px;"><col style="width: 80px;">
<col style="width: 80px;"><col style="width: 80px;"><col style="width: 80px;">
<col style="width: 80px;"><col style="width: 80px;"><col style="width: 80px;">
</colgroup>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$\circ$</th>
<th style="border: 1px solid black; text-align: right;">$e$</th>
<th style="border: 1px solid black; text-align: right;">$r_1$</th>
<th style="border: 1px solid black; text-align: right;">$r_2$</th>
<th style="border: 1px solid black; text-align: right;">$r_3$</th>
<th style="border: 1px solid black; text-align: right;">$f_v$</th>
<th style="border: 1px solid black; text-align: right;">$f_h$</th>
<th style="border: 1px solid black; text-align: right;">$f_{d_1}$</th>
<th style="border: 1px solid black; text-align: right;">$f_{d_2}$</th>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$e$</th>
<td style="border: 1px solid black; text-align: right;">$e$</td><td style="border: 1px solid black; text-align: right;">$r_1$</td><td style="border: 1px solid black; text-align: right;">$r_2$</td><td style="border: 1px solid black; text-align: right;">$r_3$</td><td style="border: 1px solid black; text-align: right;">$f_v$</td><td style="border: 1px solid black; text-align: right;">$f_h$</td><td style="border: 1px solid black; text-align: right;">$f_{d_1}$</td><td style="border: 1px solid black; text-align: right;">$f_{d_2}$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$r_1$</th>
<td style="border: 1px solid black; text-align: right;">$r_1$</td><td style="border: 1px solid black; text-align: right;">$r_2$</td><td style="border: 1px solid black; text-align: right;">$r_3$</td><td style="border: 1px solid black; text-align: right;">$e$</td><td style="border: 1px solid black; text-align: right;">$f_{d_2}$</td><td style="border: 1px solid black; text-align: right;">$f_{d_1}$</td><td style="border: 1px solid black; text-align: right;">$f_v$</td><td style="border: 1px solid black; text-align: right;">$f_h$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$r_2$</th>
<td style="border: 1px solid black; text-align: right;">$r_2$</td><td style="border: 1px solid black; text-align: right;">$r_3$</td><td style="border: 1px solid black; text-align: right;">$e$</td><td style="border: 1px solid black; text-align: right;">$r_1$</td><td style="border: 1px solid black; text-align: right;">$f_h$</td><td style="border: 1px solid black; text-align: right;">$f_v$</td><td style="border: 1px solid black; text-align: right;">$f_{d_2}$</td><td style="border: 1px solid black; text-align: right;">$f_{d_1}$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$r_3$</th>
<td style="border: 1px solid black; text-align: right;">$r_3$</td><td style="border: 1px solid black; text-align: right;">$e$</td><td style="border: 1px solid black; text-align: right;">$r_1$</td><td style="border: 1px solid black; text-align: right;">$r_2$</td><td style="border: 1px solid black; text-align: right;">$f_{d_1}$</td><td style="border: 1px solid black; text-align: right;">$f_{d_2}$</td><td style="border: 1px solid black; text-align: right;">$f_h$</td><td style="border: 1px solid black; text-align: right;">$f_v$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$f_v$</th>
<td style="border: 1px solid black; text-align: right;">$f_v$</td><td style="border: 1px solid black; text-align: right;">$f_{d_1}$</td><td style="border: 1px solid black; text-align: right;">$f_h$</td><td style="border: 1px solid black; text-align: right;">$f_{d_2}$</td><td style="border: 1px solid black; text-align: right;">$e$</td><td style="border: 1px solid black; text-align: right;">$r_2$</td><td style="border: 1px solid black; text-align: right;">$r_1$</td><td style="border: 1px solid black; text-align: right;">$r_3$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$f_h$</th>
<td style="border: 1px solid black; text-align: right;">$f_h$</td><td style="border: 1px solid black; text-align: right;">$f_{d_2}$</td><td style="border: 1px solid black; text-align: right;">$f_v$</td><td style="border: 1px solid black; text-align: right;">$f_{d_1}$</td><td style="border: 1px solid black; text-align: right;">$r_2$</td><td style="border: 1px solid black; text-align: right;">$e$</td><td style="border: 1px solid black; text-align: right;">$r_3$</td><td style="border: 1px solid black; text-align: right;">$r_1$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$f_{d_1}$</th>
<td style="border: 1px solid black; text-align: right;">$f_{d_1}$</td><td style="border: 1px solid black; text-align: right;">$f_h$</td><td style="border: 1px solid black; text-align: right;">$f_{d_2}$</td><td style="border: 1px solid black; text-align: right;">$f_v$</td><td style="border: 1px solid black; text-align: right;">$r_3$</td><td style="border: 1px solid black; text-align: right;">$r_1$</td><td style="border: 1px solid black; text-align: right;">$e$</td><td style="border: 1px solid black; text-align: right;">$r_2$</td>
</tr>
<tr>
<th style="border: 1px solid black; height: 45px; text-align: right;">$f_{d_2}$</th>
<td style="border: 1px solid black; text-align: right;">$f_{d_2}$</td><td style="border: 1px solid black; text-align: right;">$f_v$</td><td style="border: 1px solid black; text-align: right;">$f_{d_1}$</td><td style="border: 1px solid black; text-align: right;">$f_h$</td><td style="border: 1px solid black; text-align: right;">$r_1$</td><td style="border: 1px solid black; text-align: right;">$r_3$</td><td style="border: 1px solid black; text-align: right;">$r_2$</td><td style="border: 1px solid black; text-align: right;">$e$</td>
</tr>
</table>

---

## Subgroup Lattice for the Symmetries of the Square

```{mermaid}
flowchart TB
    D4["D<sub>4</sub>"]

    R["{e, r<sub>1</sub>, r<sub>2</sub>, r<sub>3</sub>}"]
    VH["{e, r<sub>2</sub>, f<sub>v</sub>, f<sub>h</sub>}"]
    DD["{e, r<sub>2</sub>, f<sub>d1</sub>, f<sub>d2</sub>}"]

    R2["{e, r<sub>2</sub>}"]
    FV["{e, f<sub>v</sub>}"]
    FH["{e, f<sub>h</sub>}"]
    FD1["{e, f<sub>d1</sub>}"]
    FD2["{e, f<sub>d2</sub>}"]

    E["{e}"]

    D4 --- R
    D4 --- VH
    D4 --- DD

    R --- R2
    VH --- R2
    DD --- R2

    VH --- FV
    VH --- FH
    DD --- FD1
    DD --- FD2

    R2 --- E
    FV --- E
    FH --- E
    FD1 --- E
    FD2 --- E
```

---




## Cayley Table for $\mathbb{Z}_8$

<table style="border-collapse: collapse; table-layout: fixed; width: 720px; font-size: 0.72em;">

<colgroup>

<col style="width: 80px;"><col style="width: 80px;"><col style="width: 80px;">

<col style="width: 80px;"><col style="width: 80px;"><col style="width: 80px;">

<col style="width: 80px;"><col style="width: 80px;"><col style="width: 80px;">

</colgroup>

<tr>

<th style="border: 1px solid black; height: 45px; text-align: right;">$+$</th>

<th style="border: 1px solid black; text-align: right;">$0$</th>

<th style="border: 1px solid black; text-align: right;">$1$</th>

<th style="border: 1px solid black; text-align: right;">$2$</th>

<th style="border: 1px solid black; text-align: right;">$3$</th>

<th style="border: 1px solid black; text-align: right;">$4$</th>

<th style="border: 1px solid black; text-align: right;">$5$</th>

<th style="border: 1px solid black; text-align: right;">$6$</th>

<th style="border: 1px solid black; text-align: right;">$7$</th>

</tr>

<tr>

<th style="border: 1px solid black; height: 45px; text-align: right;">$0$</th>

<td style="border: 1px solid black; text-align: right;">$0$</td><td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$2$</td><td style="border: 1px solid black; text-align: right;">$3$</td><td style="border: 1px solid black; text-align: right;">$4$</td><td style="border: 1px solid black; text-align: right;">$5$</td><td style="border: 1px solid black; text-align: right;">$6$</td><td style="border: 1px solid black; text-align: right;">$7$</td>

</tr>

<tr>

<th style="border: 1px solid black; height: 45px; text-align: right;">$1$</th>

<td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$2$</td><td style="border: 1px solid black; text-align: right;">$3$</td><td style="border: 1px solid black; text-align: right;">$4$</td><td style="border: 1px solid black; text-align: right;">$5$</td><td style="border: 1px solid black; text-align: right;">$6$</td><td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$0$</td>

</tr>

<tr>

<th style="border: 1px solid black; height: 45px; text-align: right;">$2$</th>

<td style="border: 1px solid black; text-align: right;">$2$</td><td style="border: 1px solid black; text-align: right;">$3$</td><td style="border: 1px solid black; text-align: right;">$4$</td><td style="border: 1px solid black; text-align: right;">$5$</td><td style="border: 1px solid black; text-align: right;">$6$</td><td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$0$</td><td style="border: 1px solid black; text-align: right;">$1$</td>

</tr>

<tr>

<th style="border: 1px solid black; height: 45px; text-align: right;">$3$</th>

<td style="border: 1px solid black; text-align: right;">$3$</td><td style="border: 1px solid black; text-align: right;">$4$</td><td style="border: 1px solid black; text-align: right;">$5$</td><td style="border: 1px solid black; text-align: right;">$6$</td><td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$0$</td><td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$2$</td>

</tr>

<tr>

<th style="border: 1px solid black; height: 45px; text-align: right;">$4$</th>

<td style="border: 1px solid black; text-align: right;">$4$</td><td style="border: 1px solid black; text-align: right;">$5$</td><td style="border: 1px solid black; text-align: right;">$6$</td><td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$0$</td><td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$2$</td><td style="border: 1px solid black; text-align: right;">$3$</td>

</tr>

<tr>

<th style="border: 1px solid black; height: 45px; text-align: right;">$5$</th>

<td style="border: 1px solid black; text-align: right;">$5$</td><td style="border: 1px solid black; text-align: right;">$6$</td><td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$0$</td><td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$2$</td><td style="border: 1px solid black; text-align: right;">$3$</td><td style="border: 1px solid black; text-align: right;">$4$</td>

</tr>

<tr>

<th style="border: 1px solid black; height: 45px; text-align: right;">$6$</th>

<td style="border: 1px solid black; text-align: right;">$6$</td><td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$0$</td><td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$2$</td><td style="border: 1px solid black; text-align: right;">$3$</td><td style="border: 1px solid black; text-align: right;">$4$</td><td style="border: 1px solid black; text-align: right;">$5$</td>

</tr>

<tr>

<th style="border: 1px solid black; height: 45px; text-align: right;">$7$</th>

<td style="border: 1px solid black; text-align: right;">$7$</td><td style="border: 1px solid black; text-align: right;">$0$</td><td style="border: 1px solid black; text-align: right;">$1$</td><td style="border: 1px solid black; text-align: right;">$2$</td><td style="border: 1px solid black; text-align: right;">$3$</td><td style="border: 1px solid black; text-align: right;">$4$</td><td style="border: 1px solid black; text-align: right;">$5$</td><td style="border: 1px solid black; text-align: right;">$6$</td>

</tr>

</table>

---

## Subgroup Lattice for $\mathbb{Z}_8$

```{mermaid}
flowchart TB

    Z["ℤ<sub>8</sub> = {0, 1, 2, 3, 4, 5, 6, 7}"]

    H4["⟨2⟩ = {0, 2, 4, 6}"]

    H2["⟨4⟩ = {0, 4}"]

    E["{0}"]

    Z --- H4

    H4 --- H2

    H2 --- E
```    